-- ============================================================================
-- INSTRUMENT CATALOG SEED (ADR-033)
-- Version: V6
-- Description: Wipe existing positions and seed instrument catalog from
--              GPW (Warsaw Stock Exchange) main market instruments.
--              Instruments become system-managed master data.
-- Source: GPW main market listing (stockanalysis.com/Stooq tickers)
-- ============================================================================

-- Step 1: Clean slate — DB is nearly empty during early development
DELETE FROM account_holdings;
DELETE FROM positions;
DELETE FROM instruments;

-- Step 2: Seed instrument catalog — GPW main market stocks
INSERT INTO instruments (symbol, name, instrument_type, currency, version)
VALUES
    -- === GPW GlobalConnect (international stocks listed on GPW) ===
    ('NVDA',  'NVIDIA Corporation',               'STOCK', 'PLN', 0),
    ('AAPL',  'Apple Inc.',                        'STOCK', 'PLN', 0),
    ('GOGL',  'Alphabet Inc.',                     'STOCK', 'PLN', 0),
    ('MSFT',  'Microsoft Corporation',             'STOCK', 'PLN', 0),
    ('AMZN',  'Amazon.com Inc.',                   'STOCK', 'PLN', 0),
    ('META',  'Meta Platforms Inc.',                'STOCK', 'PLN', 0),
    ('TSLA',  'Tesla Inc.',                        'STOCK', 'PLN', 0),
    ('JPM',   'JPMorgan Chase & Co.',              'STOCK', 'PLN', 0),
    ('VISA',  'Visa Inc.',                         'STOCK', 'PLN', 0),
    ('ASML',  'ASML Holding N.V.',                 'STOCK', 'PLN', 0),
    ('AMD',   'Advanced Micro Devices Inc.',        'STOCK', 'PLN', 0),
    ('NFLX',  'Netflix Inc.',                      'STOCK', 'PLN', 0),
    ('SAP',   'SAP SE',                            'STOCK', 'PLN', 0),
    ('ITX',   'Industria de Diseno Textil S.A.',   'STOCK', 'PLN', 0),
    ('SAN',   'Banco Santander S.A.',              'STOCK', 'PLN', 0),
    ('ALV',   'Allianz SE',                        'STOCK', 'PLN', 0),
    ('UCG',   'UniCredit S.p.A.',                  'STOCK', 'PLN', 0),
    ('NIKE',  'NIKE Inc.',                         'STOCK', 'PLN', 0),
    ('MBG',   'Mercedes-Benz Group AG',            'STOCK', 'PLN', 0),
    ('BMW',   'Bayerische Motoren Werke AG',       'STOCK', 'PLN', 0),
    ('BAY',   'Bayer AG',                          'STOCK', 'PLN', 0),
    ('RWE',   'RWE AG',                            'STOCK', 'PLN', 0),

    -- === WIG20 & mWIG40 — Large and mid-cap Polish stocks ===
    ('PKN',   'Orlen S.A.',                        'STOCK', 'PLN', 0),
    ('PKO',   'PKO Bank Polski S.A.',              'STOCK', 'PLN', 0),
    ('CEZ',   'CEZ a.s.',                          'STOCK', 'PLN', 0),
    ('SPL',   'Santander Bank Polska S.A.',        'STOCK', 'PLN', 0),
    ('KGH',   'KGHM Polska Miedz S.A.',           'STOCK', 'PLN', 0),
    ('PEO',   'Bank Pekao S.A.',                   'STOCK', 'PLN', 0),
    ('PZU',   'PZU S.A.',                          'STOCK', 'PLN', 0),
    ('JMT',   'Jeronimo Martins SGPS S.A.',        'STOCK', 'PLN', 0),
    ('ING',   'ING Bank Slaski S.A.',              'STOCK', 'PLN', 0),
    ('MBK',   'mBank S.A.',                        'STOCK', 'PLN', 0),
    ('DNP',   'Dino Polska S.A.',                  'STOCK', 'PLN', 0),
    ('LPP',   'LPP S.A.',                          'STOCK', 'PLN', 0),
    ('INPT',  'InPost S.A.',                       'STOCK', 'PLN', 0),
    ('KRK',   'Krka d.d.',                         'STOCK', 'PLN', 0),
    ('ALE',   'Allegro.eu S.A.',                   'STOCK', 'PLN', 0),
    ('MOL',   'MOL Hungarian Oil and Gas Plc',     'STOCK', 'PLN', 0),
    ('CDR',   'CD Projekt S.A.',                   'STOCK', 'PLN', 0),
    ('PGE',   'PGE Polska Grupa Energetyczna S.A.','STOCK', 'PLN', 0),
    ('ZAL',   'Zalando SE',                        'STOCK', 'PLN', 0),
    ('BNP',   'BNP Paribas Bank Polska S.A.',      'STOCK', 'PLN', 0),
    ('ZAB',   'Zabka Group S.A.',                  'STOCK', 'PLN', 0),
    ('MIL',   'Bank Millennium S.A.',              'STOCK', 'PLN', 0),
    ('TPE',   'Tauron Polska Energia S.A.',        'STOCK', 'PLN', 0),
    ('BDX',   'Budimex S.A.',                      'STOCK', 'PLN', 0),
    ('OPL',   'Orange Polska S.A.',                'STOCK', 'PLN', 0),
    ('PCO',   'Pepco Group N.V.',                  'STOCK', 'PLN', 0),
    ('ALR',   'Alior Bank S.A.',                   'STOCK', 'PLN', 0),
    ('BHW',   'Bank Handlowy w Warszawie S.A.',    'STOCK', 'PLN', 0),
    ('BFT',   'Benefit Systems S.A.',              'STOCK', 'PLN', 0),
    ('ENA',   'ENEA S.A.',                         'STOCK', 'PLN', 0),
    ('ACP',   'Asseco Poland S.A.',                'STOCK', 'PLN', 0),
    ('KTY',   'Grupa Kety S.A.',                   'STOCK', 'PLN', 0),
    ('XTB',   'XTB S.A.',                          'STOCK', 'PLN', 0),
    ('MDV',   'CCC S.A.',                          'STOCK', 'PLN', 0),
    ('KRU',   'Kruk S.A.',                         'STOCK', 'PLN', 0),
    ('CPI',   'CPI Europe AG',                     'STOCK', 'PLN', 0),
    ('CAR',   'Inter Cars S.A.',                   'STOCK', 'PLN', 0),
    ('ENG',   'Energa S.A.',                       'STOCK', 'PLN', 0),
    ('CPS',   'Cyfrowy Polsat S.A.',               'STOCK', 'PLN', 0),
    ('DOM',   'Dom Development S.A.',              'STOCK', 'PLN', 0),
    ('KER',   'Kernel Holding S.A.',               'STOCK', 'PLN', 0),
    ('DIA',   'Diagnostyka S.A.',                  'STOCK', 'PLN', 0),
    ('NWG',   'Newag S.A.',                        'STOCK', 'PLN', 0),
    ('OPG',   'CPI FIM S.A.',                      'STOCK', 'PLN', 0),
    ('DVL',   'Develia S.A.',                      'STOCK', 'PLN', 0),
    ('SPH',   'Sopharma AD',                       'STOCK', 'PLN', 0),
    ('PEP',   'Polenergia S.A.',                   'STOCK', 'PLN', 0),
    ('NEU',   'NEUCA S.A.',                        'STOCK', 'PLN', 0),
    ('ASE',   'Asseco South Eastern Europe S.A.',  'STOCK', 'PLN', 0),
    ('GPW',   'GPW S.A.',                          'STOCK', 'PLN', 0),
    ('JSW',   'JSW S.A.',                          'STOCK', 'PLN', 0),
    ('CBF',   'Cyber_Folks S.A.',                  'STOCK', 'PLN', 0),
    ('GPP',   'Grupa Pracuj S.A.',                 'STOCK', 'PLN', 0),
    ('VRC',   'Vercom S.A.',                       'STOCK', 'PLN', 0),
    ('ARH',   'Archicom S.A.',                     'STOCK', 'PLN', 0),
    ('EAT',   'AmRest Holdings SE',                'STOCK', 'PLN', 0),
    ('ABS',   'Asseco Business Solutions S.A.',    'STOCK', 'PLN', 0),
    ('SNT',   'Synektik S.A.',                     'STOCK', 'PLN', 0),

    -- === sWIG80 & smaller GPW main market stocks ===
    ('1AT',   'Atal S.A.',                         'STOCK', 'PLN', 0),
    ('MNC',   'Mennica Polska S.A.',               'STOCK', 'PLN', 0),
    ('PXM',   'Polimex-Mostostal S.A.',            'STOCK', 'PLN', 0),
    ('RBW',   'Rainbow Tours S.A.',                'STOCK', 'PLN', 0),
    ('MLG',   'MLP Group S.A.',                    'STOCK', 'PLN', 0),
    ('APR',   'Auto Partner S.A.',                 'STOCK', 'PLN', 0),
    ('ECH',   'Echo Investment S.A.',              'STOCK', 'PLN', 0),
    ('TRK',   'Trakcja S.A.',                      'STOCK', 'PLN', 0),
    ('ASB',   'ASBISc Enterprises Plc',            'STOCK', 'PLN', 0),
    ('ABE',   'AB S.A.',                           'STOCK', 'PLN', 0),
    ('GEA',   'Grenevia S.A.',                     'STOCK', 'PLN', 0),
    ('MUR',   'Murapol S.A.',                      'STOCK', 'PLN', 0),
    ('WPL',   'Wirtualna Polska Holding S.A.',     'STOCK', 'PLN', 0),
    ('PLW',   'PlayWay S.A.',                      'STOCK', 'PLN', 0),
    ('CRI',   'Creotech Instruments S.A.',         'STOCK', 'PLN', 0),
    ('ATT',   'Grupa Azoty S.A.',                  'STOCK', 'PLN', 0),
    ('SGN',   'Sygnity S.A.',                      'STOCK', 'PLN', 0),
    ('GTC',   'Globe Trade Centre S.A.',           'STOCK', 'PLN', 0),
    ('MCI',   'MCI Capital ASI S.A.',              'STOCK', 'PLN', 0),
    ('MRB',   'Mirbud S.A.',                       'STOCK', 'PLN', 0),
    ('VOX',   'Voxel S.A.',                        'STOCK', 'PLN', 0),
    ('TOR',   'Torpol S.A.',                       'STOCK', 'PLN', 0),
    ('PCR',   'PCC Rokita S.A.',                   'STOCK', 'PLN', 0),
    ('LBW',   'Lubawa S.A.',                       'STOCK', 'PLN', 0),
    ('TAR',   'Tarczynski S.A.',                   'STOCK', 'PLN', 0),
    ('STP',   'Stalprodukt S.A.',                  'STOCK', 'PLN', 0),
    ('MBR',   'Mo-BRUK S.A.',                      'STOCK', 'PLN', 0),
    ('SHO',   'Shoper S.A.',                       'STOCK', 'PLN', 0),
    ('AST',   'Astarta Holding Plc',               'STOCK', 'PLN', 0),
    ('SEL',   'Selena FM S.A.',                    'STOCK', 'PLN', 0),
    ('CLN',   'Celon Pharma S.A.',                 'STOCK', 'PLN', 0),
    ('COG',   'Cognor Holding S.A.',               'STOCK', 'PLN', 0),
    ('VRG',   'VRG S.A.',                          'STOCK', 'PLN', 0),
    ('EHG',   'Eurohold Bulgaria AD',              'STOCK', 'PLN', 0),
    ('DBC',   'Debica S.A.',                       'STOCK', 'PLN', 0),
    ('KGN',   'Kogeneracja S.A.',                  'STOCK', 'PLN', 0),
    ('CMP',   'Comp S.A.',                         'STOCK', 'PLN', 0),
    ('BRS',   'Boryszew S.A.',                     'STOCK', 'PLN', 0),
    ('WWL',   'Wawel S.A.',                        'STOCK', 'PLN', 0),
    ('OPN',   'Oponeo.pl S.A.',                    'STOCK', 'PLN', 0),
    ('IMC',   'IMC S.A.',                          'STOCK', 'PLN', 0),
    ('ENT',   'Enter Air S.A.',                    'STOCK', 'PLN', 0),
    ('UNT',   'Unimot S.A.',                       'STOCK', 'PLN', 0),
    ('SKA',   'Sniezka S.A.',                      'STOCK', 'PLN', 0),
    ('BOS',   'Bank Ochrony Srodowiska S.A.',      'STOCK', 'PLN', 0),
    ('HUG',   'Huuuge Inc.',                       'STOCK', 'PLN', 0),
    ('DAT',   'DataWalk S.A.',                     'STOCK', 'PLN', 0),
    ('TXT',   'Text S.A.',                         'STOCK', 'PLN', 0),
    ('PCE',   'Grupa Azoty Police S.A.',           'STOCK', 'PLN', 0),
    ('TMR',   'Tatry mountain resorts a.s.',       'STOCK', 'PLN', 0),
    ('ZEP',   'ZE PAK S.A.',                       'STOCK', 'PLN', 0),
    ('ZAP',   'Zaklady Azotowe Pulawy S.A.',       'STOCK', 'PLN', 0),
    ('EUR',   'Eurocash S.A.',                     'STOCK', 'PLN', 0),
    ('DAD',   'Dadelo S.A.',                       'STOCK', 'PLN', 0),
    ('BST',   'BEST S.A.',                         'STOCK', 'PLN', 0),
    ('DCR',   'Decora S.A.',                       'STOCK', 'PLN', 0),
    ('SLV',   'Selvita S.A.',                      'STOCK', 'PLN', 0),
    ('GRX',   'GreenX Metals Ltd',                 'STOCK', 'PLN', 0),
    ('APT',   'Apator S.A.',                       'STOCK', 'PLN', 0),
    ('DEK',   'Dekpol S.A.',                       'STOCK', 'PLN', 0),
    ('TOA',   'TOYA S.A.',                         'STOCK', 'PLN', 0),
    ('STX',   'Stalexport Autostrady S.A.',        'STOCK', 'PLN', 0),
    ('LWB',   'Lubelski Wegiel Bogdanka S.A.',     'STOCK', 'PLN', 0),
    ('FRO',   'Ferro S.A.',                        'STOCK', 'PLN', 0),
    ('TEN',   'Ten Square Games S.A.',             'STOCK', 'PLN', 0),
    ('QRS',   'Quercus TFI S.A.',                  'STOCK', 'PLN', 0),
    ('ENE',   'Enel-Med S.A.',                     'STOCK', 'PLN', 0),
    ('OBL',   'Orzel Bialy S.A.',                  'STOCK', 'PLN', 0),
    ('RVU',   'Ryvu Therapeutics S.A.',            'STOCK', 'PLN', 0),
    ('PKP',   'PKP Cargo S.A.',                    'STOCK', 'PLN', 0),
    ('ATC',   'Arctic Paper S.A.',                 'STOCK', 'PLN', 0),
    ('VOT',   'Votum S.A.',                        'STOCK', 'PLN', 0),
    ('SNK',   'Sanok Rubber Company S.A.',         'STOCK', 'PLN', 0),
    ('OND',   'Onde S.A.',                         'STOCK', 'PLN', 0),
    ('FTE',   'Forte S.A.',                        'STOCK', 'PLN', 0),
    ('SPR',   'Spyrosoft S.A.',                    'STOCK', 'PLN', 0),
    ('ATR',   'Atrem S.A.',                        'STOCK', 'PLN', 0),
    ('UNI',   'Unibep S.A.',                       'STOCK', 'PLN', 0),
    ('ELT',   'Elektrotim S.A.',                   'STOCK', 'PLN', 0),
    ('PHN',   'Polski Holding Nieruchomosci S.A.', 'STOCK', 'PLN', 0),
    ('LKD',   'Lokum Deweloper S.A.',              'STOCK', 'PLN', 0),
    ('SCP',   'Scope Fluidics S.A.',               'STOCK', 'PLN', 0),
    ('RAF',   'Rafamet S.A.',                      'STOCK', 'PLN', 0),
    ('CIG',   'CI Games SE',                       'STOCK', 'PLN', 0),
    ('RWL',   'Rawlplug S.A.',                     'STOCK', 'PLN', 0),
    ('AMC',   'Amica S.A.',                        'STOCK', 'PLN', 0),
    ('MGT',   'Mangata Holding S.A.',              'STOCK', 'PLN', 0),
    ('CTX',   'Captor Therapeutics S.A.',          'STOCK', 'PLN', 0),
    ('BLO',   'Bloober Team S.A.',                 'STOCK', 'PLN', 0),
    ('WLT',   'Wielton S.A.',                      'STOCK', 'PLN', 0),
    ('VGO',   'VIGO Photonics S.A.',               'STOCK', 'PLN', 0),
    ('KPL',   'Kino Polska TV S.A.',               'STOCK', 'PLN', 0),
    ('MSZ',   'Mostostal Zabrze S.A.',             'STOCK', 'PLN', 0),
    ('AMB',   'Ambra S.A.',                        'STOCK', 'PLN', 0),
    ('ANR',   'Answear.com S.A.',                  'STOCK', 'PLN', 0),
    ('ACT',   'Action S.A.',                       'STOCK', 'PLN', 0),
    ('CRJ',   'Creepy Jar S.A.',                   'STOCK', 'PLN', 0),
    ('BCX',   'Bioceltix S.A.',                    'STOCK', 'PLN', 0),
    ('AGO',   'Agora S.A.',                        'STOCK', 'PLN', 0),
    ('SCW',   'Scanway S.A.',                      'STOCK', 'PLN', 0),
    ('ERB',   'Erbud S.A.',                        'STOCK', 'PLN', 0),
    ('PCX',   'PCC Exol S.A.',                     'STOCK', 'PLN', 0),
    ('CFI',   'CFI Holding S.A.',                  'STOCK', 'PLN', 0),
    ('WAS',   'Wasko S.A.',                        'STOCK', 'PLN', 0),
    ('MRC',   'Mercator Medical S.A.',             'STOCK', 'PLN', 0),
    ('SWM',   'Software Mansion S.A.',             'STOCK', 'PLN', 0),
    ('CAV',   'Cavatina Holding S.A.',             'STOCK', 'PLN', 0),
    ('MVP',   'Marvipol Development S.A.',         'STOCK', 'PLN', 0),
    ('BIO',   'Bioton S.A.',                       'STOCK', 'PLN', 0),
    ('GKI',   'Grupa Kapitalowa Immobile S.A.',    'STOCK', 'PLN', 0),
    ('11B',   '11 bit studios S.A.',               'STOCK', 'PLN', 0),
    ('CLD',   'Cloud Technologies S.A.',           'STOCK', 'PLN', 0),
    ('INP',   'Inpro S.A.',                        'STOCK', 'PLN', 0),
    ('ULM',   'ULMA Construccion Polska S.A.',     'STOCK', 'PLN', 0),
    ('ATG',   'ATM Grupa S.A.',                    'STOCK', 'PLN', 0),
    ('BMC',   'Bumech S.A.',                       'STOCK', 'PLN', 0),
    ('MDG',   'Medicalgorithmics S.A.',            'STOCK', 'PLN', 0),
    ('WTN',   'Wittchen S.A.',                     'STOCK', 'PLN', 0),
    ('PBX',   'Pekabex S.A.',                      'STOCK', 'PLN', 0),
    ('INK',   'Instal Krakow S.A.',                'STOCK', 'PLN', 0),
    ('CLC',   'Columbus Energy S.A.',              'STOCK', 'PLN', 0),
    ('ODL',   'Odlewnie Polskie S.A.',             'STOCK', 'PLN', 0),
    ('ZUE',   'ZUE S.A.',                          'STOCK', 'PLN', 0),
    ('SVE',   'Synthaverse S.A.',                  'STOCK', 'PLN', 0),
    ('PAS',   'Passus S.A.',                       'STOCK', 'PLN', 0),
    ('SKH',   'Skarbiec Holding S.A.',             'STOCK', 'PLN', 0),
    ('MAK',   'Makarony Polskie S.A.',             'STOCK', 'PLN', 0),
    ('SWG',   'Seco/Warwick S.A.',                 'STOCK', 'PLN', 0),
    ('MFO',   'MFO S.A.',                          'STOCK', 'PLN', 0),
    ('NVT',   'Novita S.A.',                       'STOCK', 'PLN', 0),
    ('LTX',   'Lentex S.A.',                       'STOCK', 'PLN', 0),
    ('IFI',   'Ifirma S.A.',                       'STOCK', 'PLN', 0),
    ('ALL',   'Ailleron S.A.',                     'STOCK', 'PLN', 0),
    ('GRN',   'Grodno S.A.',                       'STOCK', 'PLN', 0),
    ('SON',   'Sonel S.A.',                        'STOCK', 'PLN', 0),
    ('ACG',   'AC S.A.',                           'STOCK', 'PLN', 0),
    ('INL',   'Introl S.A.',                       'STOCK', 'PLN', 0),
    ('JRH',   'JR Holding ASI S.A.',               'STOCK', 'PLN', 0),
    ('ART',   'Artifex Mundi S.A.',                'STOCK', 'PLN', 0),
    ('OTS',   'OT Logistics S.A.',                 'STOCK', 'PLN', 0),
    ('CTS',   'City Service SE',                   'STOCK', 'PLN', 0),
    ('SFG',   'Silvano Fashion Group',             'STOCK', 'PLN', 0),
    ('APN',   'Aplisens S.A.',                     'STOCK', 'PLN', 0),
    ('HEL',   'Helio S.A.',                        'STOCK', 'PLN', 0),
    ('MON',   'Monnari Trade S.A.',                'STOCK', 'PLN', 0),
    ('XPL',   'Xplus S.A.',                        'STOCK', 'PLN', 0),
    ('XTP',   'XTPL S.A.',                         'STOCK', 'PLN', 0),
    ('VIN',   'Vindexus S.A.',                     'STOCK', 'PLN', 0),
    ('NVA',   'P.A. Nova S.A.',                    'STOCK', 'PLN', 0),
    ('OML',   'One More Level S.A.',               'STOCK', 'PLN', 0),
    ('RNK',   'Rank Progress S.A.',                'STOCK', 'PLN', 0),
    ('MOC',   'Molecure S.A.',                     'STOCK', 'PLN', 0),
    ('WIK',   'Wikana S.A.',                       'STOCK', 'PLN', 0),
    ('NTT',   'NTT System S.A.',                   'STOCK', 'PLN', 0),
    ('AQU',   'Aqua S.A.',                         'STOCK', 'PLN', 0),
    ('MSW',   'Mostostal Warszawa S.A.',           'STOCK', 'PLN', 0),
    ('YAN',   'Yanosik S.A.',                      'STOCK', 'PLN', 0),
    ('OTM',   'Otmuchow S.A.',                     'STOCK', 'PLN', 0),
    ('STF',   'Stalprofil S.A.',                   'STOCK', 'PLN', 0),
    ('KVT',   'Krynica Vitamin S.A.',              'STOCK', 'PLN', 0),
    ('MLS',   'ML System S.A.',                    'STOCK', 'PLN', 0),
    ('PCF',   'PCF Group S.A.',                    'STOCK', 'PLN', 0),
    ('B24',   'Brand 24 S.A.',                     'STOCK', 'PLN', 0),
    ('IPE',   'IPOPEMA Securities S.A.',           'STOCK', 'PLN', 0),
    ('ATP',   'Atlanta Poland S.A.',               'STOCK', 'PLN', 0),
    ('RPC',   'Ropczyce S.A.',                     'STOCK', 'PLN', 0),
    ('MAB',   'Mabion S.A.',                       'STOCK', 'PLN', 0),
    ('SFD',   'SFD S.A.',                          'STOCK', 'PLN', 0),
    ('SVRS',  'Silvair Inc.',                      'STOCK', 'PLN', 0),
    ('PTG',   'Poltreg S.A.',                      'STOCK', 'PLN', 0),
    ('ATD',   'Atende S.A.',                       'STOCK', 'PLN', 0),
    ('4MS',   '4MASS S.A.',                        'STOCK', 'PLN', 0),
    ('PJP',   'PJP Makrum S.A.',                   'STOCK', 'PLN', 0),
    ('QNA',   'QNA Technology S.A.',               'STOCK', 'PLN', 0),
    ('LSI',   'LSI Software S.A.',                 'STOCK', 'PLN', 0),
    ('ETL',   'Eurotel S.A.',                      'STOCK', 'PLN', 0),
    ('PEN',   'Photon Energy N.V.',                'STOCK', 'PLN', 0),
    ('WXF',   'Warimpex Finanz AG',                'STOCK', 'PLN', 0),
    ('HOR',   'Hortico S.A.',                      'STOCK', 'PLN', 0),
    ('GRC',   'Grupa Recykl S.A.',                 'STOCK', 'PLN', 0),
    ('GTN',   'Getin Holding S.A.',                'STOCK', 'PLN', 0),
    ('HPM',   'HiProMine S.A.',                    'STOCK', 'PLN', 0),
    ('IZS',   'Izostal S.A.',                      'STOCK', 'PLN', 0),
    ('PAT',   'Patentus S.A.',                     'STOCK', 'PLN', 0),
    ('TRN',   'Trans Polonia S.A.',                'STOCK', 'PLN', 0),
    ('IMS',   'IMS S.A.',                          'STOCK', 'PLN', 0),
    ('BBT',   'BoomBit S.A.',                      'STOCK', 'PLN', 0),
    ('BOW',   'Bowim S.A.',                        'STOCK', 'PLN', 0),
    ('ZMT',   'Zamet S.A.',                        'STOCK', 'PLN', 0),
    ('MNS',   'Mennica Skarbowa S.A.',             'STOCK', 'PLN', 0),
    ('BIP',   'Bio Planet S.A.',                   'STOCK', 'PLN', 0),
    ('SNX',   'Sunex S.A.',                        'STOCK', 'PLN', 0),
    ('FOR',   'Forever Entertainment S.A.',         'STOCK', 'PLN', 0),
    ('PPS',   'Pepees S.A.',                       'STOCK', 'PLN', 0),
    ('DEL',   'Delko S.A.',                        'STOCK', 'PLN', 0),
    ('KGL',   'KGL S.A.',                          'STOCK', 'PLN', 0),
    ('APE',   'APS Energia S.A.',                  'STOCK', 'PLN', 0),
    ('PWX',   'Polwax S.A.',                       'STOCK', 'PLN', 0),
    ('ULG',   'Ultimate Games S.A.',               'STOCK', 'PLN', 0),
    ('FAB',   'Fabrity S.A.',                      'STOCK', 'PLN', 0),
    ('KOM',   'Komputronik S.A.',                  'STOCK', 'PLN', 0),
    ('SEK',   'Seko S.A.',                         'STOCK', 'PLN', 0),
    ('ENP',   'Energoaparatura S.A.',              'STOCK', 'PLN', 0),
    ('EAH',   'Esotiq & Henderson S.A.',           'STOCK', 'PLN', 0),
    ('SWG',   'Seco/Warwick S.A.',                 'STOCK', 'PLN', 0),
    ('LEN',   'Lena Lighting S.A.',                'STOCK', 'PLN', 0),
    ('LEG',   'Legimi S.A.',                       'STOCK', 'PLN', 0),
    ('KCI',   'KCI S.A.',                          'STOCK', 'PLN', 0),
    ('RLP',   'Relpol S.A.',                       'STOCK', 'PLN', 0),
    ('GOP',   'Games Operators S.A.',              'STOCK', 'PLN', 0),
    ('TLX',   'Talex S.A.',                        'STOCK', 'PLN', 0),
    ('AME',   'Advanced Medical Equipment S.A.',    'STOCK', 'PLN', 0),
    ('KOR',   'Korbank S.A.',                      'STOCK', 'PLN', 0),
    ('ACT',   'Action S.A.',                       'STOCK', 'PLN', 0),
    ('ANR',   'Answear.com S.A.',                  'STOCK', 'PLN', 0),
    ('BBD',   'BBI Development S.A.',              'STOCK', 'PLN', 0),
    ('CPR',   'Compremum S.A.',                    'STOCK', 'PLN', 0),
    ('3RG',   '3R Games S.A.',                     'STOCK', 'PLN', 0),
    ('IPO',   'Intersport Polska S.A.',            'STOCK', 'PLN', 0),
    ('PRM',   'Prochem S.A.',                      'STOCK', 'PLN', 0),
    ('BMX',   'BioMaxima S.A.',                    'STOCK', 'PLN', 0),
    ('FSG',   'FASING S.A.',                       'STOCK', 'PLN', 0),
    ('BCS',   'Big Cheese Studio S.A.',            'STOCK', 'PLN', 0),
    ('MLB',   'MakoLab S.A.',                      'STOCK', 'PLN', 0),
    ('BGD',   'Biogened S.A.',                     'STOCK', 'PLN', 0),
    ('HRS',   'Herkules S.A.',                     'STOCK', 'PLN', 0),
    ('CAP',   'Capitea S.A.',                      'STOCK', 'PLN', 0),
    ('QNT',   'Quantum Software S.A.',             'STOCK', 'PLN', 0),
    ('APS',   'Automatyka-Pomiary-Sterowanie S.A.','STOCK', 'PLN', 0),
    ('ENI',   'Energoinstal S.A.',                 'STOCK', 'PLN', 0),
    ('CDL',   'CDRL S.A.',                         'STOCK', 'PLN', 0),
    ('HDR',   'Hydrotor S.A.',                     'STOCK', 'PLN', 0),
    ('GEN',   'Genomed S.A.',                      'STOCK', 'PLN', 0),
    ('DTR',   'Digitree Group S.A.',               'STOCK', 'PLN', 0),
    ('IZB',   'Izoblok S.A.',                      'STOCK', 'PLN', 0),
    ('PHR',   'Pharmena S.A.',                     'STOCK', 'PLN', 0),
    ('VVD',   'Vivid Games S.A.',                  'STOCK', 'PLN', 0),
    ('CIG',   'CI Games SE',                       'STOCK', 'PLN', 0),
    ('GIF',   'Gaming Factory S.A.',               'STOCK', 'PLN', 0),
    ('KBJ',   'KBJ S.A.',                          'STOCK', 'PLN', 0),
    ('RMK',   'Remak-Energomontaz S.A.',           'STOCK', 'PLN', 0),
    ('JWW',   'JWW Invest S.A.',                   'STOCK', 'PLN', 0),
    ('PRT',   'Protektor S.A.',                    'STOCK', 'PLN', 0),
    ('CPA',   'Capital Partners S.A.',             'STOCK', 'PLN', 0),
    ('HRP',   'Harper Hygienics S.A.',             'STOCK', 'PLN', 0),
    ('INC',   'INC S.A.',                          'STOCK', 'PLN', 0),
    ('MIR',   'Miraculum S.A.',                    'STOCK', 'PLN', 0),
    ('CRM',   'PZ Cormay S.A.',                    'STOCK', 'PLN', 0),
    ('06N',   'Magna Polonia S.A.',                'STOCK', 'PLN', 0),
    ('SKL',   'Skyline Investment S.A.',           'STOCK', 'PLN', 0),
    ('PUR',   'Pure Biologics S.A.',               'STOCK', 'PLN', 0),
    ('F51',   'The Farm 51 Group S.A.',            'STOCK', 'PLN', 0),
    ('WOD',   'WODKAN S.A.',                       'STOCK', 'PLN', 0),
    ('ERG',   'ERG S.A.',                          'STOCK', 'PLN', 0),
    ('MEX',   'Mex Polska S.A.',                   'STOCK', 'PLN', 0),
    ('PLI',   'Platige Image S.A.',                'STOCK', 'PLN', 0),
    ('MSP',   'Mostostal Plock S.A.',              'STOCK', 'PLN', 0),
    ('DBE',   'DB Energy S.A.',                    'STOCK', 'PLN', 0),
    ('ASM',   'ASM Group S.A.',                    'STOCK', 'PLN', 0),
    ('EFK',   'Korporacja Gospodarcza efekt S.A.', 'STOCK', 'PLN', 0),
    ('BSH',   'Bridge Solutions Hub S.A.',         'STOCK', 'PLN', 0),
    ('AAT',   'Alta S.A.',                         'STOCK', 'PLN', 0),
    ('OPM',   'OPTeam S.A.',                       'STOCK', 'PLN', 0),
    ('DGA',   'DGA S.A.',                          'STOCK', 'PLN', 0),
    ('TSG',   'Tesgas S.A.',                       'STOCK', 'PLN', 0),
    ('MPY',   'mPay S.A.',                         'STOCK', 'PLN', 0),

    -- === GPW ETFs ===
    ('ETFSP500', 'Beta ETF S&P 500',              'ETF',   'PLN', 0),
    ('ETFDAX',   'Beta ETF DAX',                   'ETF',   'PLN', 0),
    ('ETFW20L',  'Beta ETF WIG20 Lev',             'ETF',   'PLN', 0),
    ('ETFW20S',  'Beta ETF WIG20 Short',           'ETF',   'PLN', 0),
    ('ETFW20TR', 'Beta ETF WIG20TR',               'ETF',   'PLN', 0),
    ('ETFWIG',   'Beta ETF mWIG40TR',              'ETF',   'PLN', 0)
ON CONFLICT (symbol) DO NOTHING;

-- ============================================================================
-- END OF MIGRATION V6
-- Total: ~280 GPW main market instruments + 6 ETFs
-- ============================================================================
