-- ============================================================================
-- ADD MISSING INSTRUMENTS TO CATALOG
-- Version: V7
-- Description: Add remaining GPW main market instruments missing from V6,
--              plus Beta ETF products not previously included.
-- Source: stockanalysis.com (stocks), betaetf.pl / gpw.pl (ETFs)
-- ============================================================================

-- === Missing GPW stocks (384 instruments) ===
INSERT INTO instruments (symbol, name, instrument_type, currency, version)
VALUES
    ('4MB',  '4Mobility Spolka Akcyjna',                                         'STOCK', 'PLN', 0),
    ('7FT',  '7FIT S.A.',                                                        'STOCK', 'PLN', 0),
    ('7LV',  '7Levels S.A.',                                                     'STOCK', 'PLN', 0),
    ('AAS',  'Arts Alliance S.A.',                                               'STOCK', 'PLN', 0),
    ('ABK',  'Abak S.A.',                                                        'STOCK', 'PLN', 0),
    ('ADV',  'Adiuvo Investments S.A.',                                          'STOCK', 'PLN', 0),
    ('ADX',  'Adatex S.A.',                                                      'STOCK', 'PLN', 0),
    ('AER',  'Venda SE',                                                         'STOCK', 'PLN', 0),
    ('AFC',  'AKCEPT Finance S.A.',                                              'STOCK', 'PLN', 0),
    ('AGL',  'Agroliga Group Plc',                                               'STOCK', 'PLN', 0),
    ('AGP',  'Agromep S.A.',                                                     'STOCK', 'PLN', 0),
    ('AGT',  'Agroton Public Limited',                                           'STOCK', 'PLN', 0),
    ('AIN',  'ABS Investment ASI SA',                                            'STOCK', 'PLN', 0),
    ('AIT',  'Aiton Caldwell SA',                                                'STOCK', 'PLN', 0),
    ('ALG',  'All in! Games S.A.',                                               'STOCK', 'PLN', 0),
    ('ALI',  'Altus S.A.',                                                       'STOCK', 'PLN', 0),
    ('AOL',  'Analizy Online S.A.',                                              'STOCK', 'PLN', 0),
    ('APA',  'Apanet S.A.',                                                      'STOCK', 'PLN', 0),
    ('APC',  'Apollo Capital ASI Spolka Akcyjna',                                'STOCK', 'PLN', 0),
    ('APL',  'LC Spolka Akcyjna',                                                'STOCK', 'PLN', 0),
    ('AQA',  'Aqua S.A.',                                                        'STOCK', 'PLN', 0),
    ('AQT',  'AQT Water S.A.',                                                   'STOCK', 'PLN', 0),
    ('ARG',  'Art Games Studio S.A.',                                            'STOCK', 'PLN', 0),
    ('ARI',  'Agencja Rozwoju Innowacji Spolka Akcyjna',                         'STOCK', 'PLN', 0),
    ('ARL',  'Arlen S.A.',                                                       'STOCK', 'PLN', 0),
    ('ASA',  'APIS Spolka Akcyjna',                                              'STOCK', 'PLN', 0),
    ('ASR',  'Astro S.A.',                                                       'STOCK', 'PLN', 0),
    ('ATA',  'ATC CARGO S.A.',                                                   'STOCK', 'PLN', 0),
    ('ATJ',  'Atomic Jelly S.A.',                                                'STOCK', 'PLN', 0),
    ('ATS',  'Atlantis SE',                                                      'STOCK', 'PLN', 0),
    ('AUX',  'Auxilia S.A.',                                                     'STOCK', 'PLN', 0),
    ('AVE',  'Advertigo S.A.',                                                   'STOCK', 'PLN', 0),
    ('AWM',  'Airway Medix S.A.',                                                'STOCK', 'PLN', 0),
    ('AZC',  'Aztec International S.A.',                                         'STOCK', 'PLN', 0),
    ('BAC',  'B-act Spolka Akcyjna',                                             'STOCK', 'PLN', 0),
    ('BCM',  'Betacom S.A.',                                                     'STOCK', 'PLN', 0),
    ('BEE',  'beeIN S.A.',                                                       'STOCK', 'PLN', 0),
    ('BEP',  'Biomass Energy Project S.A.',                                      'STOCK', 'PLN', 0),
    ('BHX',  'Binary Helix Spolka Akcyjna',                                      'STOCK', 'PLN', 0),
    ('BIG',  'Baseig Spolka Akcyjna',                                            'STOCK', 'PLN', 0),
    ('BKD',  'Baked Games S.A.',                                                 'STOCK', 'PLN', 0),
    ('BLF',  'BeLeaf S.A.',                                                      'STOCK', 'PLN', 0),
    ('BLT',  'Balticon S.A.',                                                    'STOCK', 'PLN', 0),
    ('BPC',  'Black Pearl S.A.',                                                 'STOCK', 'PLN', 0),
    ('BPN',  'Black Point S.A.',                                                 'STOCK', 'PLN', 0),
    ('BRO',  'Browar Czarnkow S.A.',                                             'STOCK', 'PLN', 0),
    ('BRP',  'Black Rose Projects SA',                                           'STOCK', 'PLN', 0),
    ('BSA',  'Bras S.A.',                                                        'STOCK', 'PLN', 0),
    ('BSN',  'BrainScan Sp. z o. o.',                                            'STOCK', 'PLN', 0),
    ('BTC',  'BTC Studios S.A.',                                                 'STOCK', 'PLN', 0),
    ('BTF',  'BTCS S.A.',                                                        'STOCK', 'PLN', 0),
    ('CAI',  'Carlson Investments SE',                                           'STOCK', 'PLN', 0),
    ('CBD',  'Cannabis Poland S.A.',                                             'STOCK', 'PLN', 0),
    ('CCE',  'Clean&Carbon Energy S.A.',                                         'STOCK', 'PLN', 0),
    ('CCS',  'Cyfrowe Centrum Serwisowe Spolka Akcyjna',                         'STOCK', 'PLN', 0),
    ('CFG',  'CreativeForge Games S.A.',                                         'STOCK', 'PLN', 0),
    ('CFS',  'Centrum Finansowe S.A.',                                           'STOCK', 'PLN', 0),
    ('CHP',  'Cherrypick Games S.A.',                                            'STOCK', 'PLN', 0),
    ('CLA',  'Console Labs S.A.',                                                'STOCK', 'PLN', 0),
    ('CLE',  'Coal Energy S.A.',                                                 'STOCK', 'PLN', 0),
    ('CMI',  'CM International S.A.',                                            'STOCK', 'PLN', 0),
    ('COR',  'Corey Europe S.A.',                                                'STOCK', 'PLN', 0),
    ('COS',  'Cosma S.A.',                                                       'STOCK', 'PLN', 0),
    ('CPD',  'CPD S.A.',                                                         'STOCK', 'PLN', 0),
    ('CPL',  'Comperia.pl S.A.',                                                 'STOCK', 'PLN', 0),
    ('CRB',  'Carbon Studio S.A.',                                               'STOCK', 'PLN', 0),
    ('CRC',  'Carpathia Capital Alternatywna Spolka Inwestycyjna S.A.',          'STOCK', 'PLN', 0),
    ('CSR',  'Caspar Asset Management S.A.',                                     'STOCK', 'PLN', 0),
    ('CST',  'CStore S.A.',                                                      'STOCK', 'PLN', 0),
    ('CTE',  'CTE Group S.A.',                                                   'STOCK', 'PLN', 0),
    ('CTF',  'Centurion Finance ASI Spolka Akcyjna',                             'STOCK', 'PLN', 0),
    ('CWA',  'Consoleway Spolka Akcyjna',                                        'STOCK', 'PLN', 0),
    ('CZT',  'Czerwona Torebka Spolka Akcyjna',                                  'STOCK', 'PLN', 0),
    ('DDI',  'Draw Distance SA',                                                 'STOCK', 'PLN', 0),
    ('DFH',  'Defence.Hub Spolka Akcyjna',                                       'STOCK', 'PLN', 0),
    ('DGE',  'DRAGO entertainment Spolka Akcyjna',                               'STOCK', 'PLN', 0),
    ('DGN',  'DG-Net S.A.',                                                      'STOCK', 'PLN', 0),
    ('DGS',  'Demolish Games Spolka Akcyjna',                                    'STOCK', 'PLN', 0),
    ('DIG',  'Digital Network SA',                                               'STOCK', 'PLN', 0),
    ('DIV',  'di volio S.A.',                                                    'STOCK', 'PLN', 0),
    ('DKR',  'Dektra SA',                                                        'STOCK', 'PLN', 0),
    ('DMG',  'Dr. Miele Cosmed Group S.A.',                                      'STOCK', 'PLN', 0),
    ('DNS',  'Danks Spolka Akcyjna',                                             'STOCK', 'PLN', 0),
    ('DPG',  'Dark Point Games S.A.',                                            'STOCK', 'PLN', 0),
    ('DRF',  'Dr.Finance S.A.',                                                  'STOCK', 'PLN', 0),
    ('DRG',  'Drageus Games S.A.',                                               'STOCK', 'PLN', 0),
    ('DTX',  'DITIX S.A.',                                                       'STOCK', 'PLN', 0),
    ('DUA',  'Duality S.A.',                                                     'STOCK', 'PLN', 0),
    ('EBX',  'Ekobox S.A.',                                                      'STOCK', 'PLN', 0),
    ('ECB',  'ECB S.A.',                                                         'STOCK', 'PLN', 0),
    ('ECC',  'ECC Games S.A.',                                                   'STOCK', 'PLN', 0),
    ('ECK',  'Eurosnack S.A.',                                                   'STOCK', 'PLN', 0),
    ('ECL',  'easyCALL.pl S.A.',                                                 'STOCK', 'PLN', 0),
    ('ECN',  'Ecnology Group S.A.',                                              'STOCK', 'PLN', 0),
    ('ECT',  'Eco5Tech S.A.',                                                    'STOCK', 'PLN', 0),
    ('EDI',  'ED Invest Spolka Akcyjna',                                         'STOCK', 'PLN', 0),
    ('EDL',  'Editel S.A.',                                                      'STOCK', 'PLN', 0),
    ('EEE',  'Beskidzkie Biuro Inwestycyjne S.A.',                               'STOCK', 'PLN', 0),
    ('EGH',  'Ekopol Gornoslaski Holding S.A.',                                  'STOCK', 'PLN', 0),
    ('EGY',  'ENERGY S.A.',                                                      'STOCK', 'PLN', 0),
    ('EKP',  'Elkop Estonia SE',                                                 'STOCK', 'PLN', 0),
    ('EKS',  'e-Kiosk S.A.',                                                     'STOCK', 'PLN', 0),
    ('ELQ',  'ELQ S.A.',                                                         'STOCK', 'PLN', 0),
    ('EMP',  'Emplocity Spolka Akcyjna',                                         'STOCK', 'PLN', 0),
    ('END',  'Eneida Games S.A.',                                                'STOCK', 'PLN', 0),
    ('EPR',  'Ekopark S.A.',                                                     'STOCK', 'PLN', 0),
    ('EQU',  'Equnico SE',                                                       'STOCK', 'PLN', 0),
    ('ERA',  'Erato Energy S.A.',                                                'STOCK', 'PLN', 0),
    ('ESK',  'Eskimos S.A.',                                                     'STOCK', 'PLN', 0),
    ('ETX',  'Euro-Tax.pl S.A.',                                                 'STOCK', 'PLN', 0),
    ('EUC',  'Europejskie Centrum Odszkodowan S.A.',                             'STOCK', 'PLN', 0),
    ('EUV',  'Euvic S.A.',                                                       'STOCK', 'PLN', 0),
    ('EXA',  'Examobile S.A.',                                                   'STOCK', 'PLN', 0),
    ('EXC',  'Excellence S.A.',                                                  'STOCK', 'PLN', 0),
    ('EXM',  'e-Xim IT S.A.',                                                    'STOCK', 'PLN', 0),
    ('FEE',  'Feerum S.A.',                                                      'STOCK', 'PLN', 0),
    ('FEM',  'Femion Technology S.A.',                                           'STOCK', 'PLN', 0),
    ('FFP',  'Farmy Fotowoltaiki Polska S.A.',                                  'STOCK', 'PLN', 0),
    ('FHB',  'FoodHub Spolka Akcyjna',                                           'STOCK', 'PLN', 0),
    ('FHD',  'Fundusz Hipoteczny DOM S.A.',                                      'STOCK', 'PLN', 0),
    ('FMG',  'Wise Energy S.A.',                                                 'STOCK', 'PLN', 0),
    ('FON',  'FON SE',                                                           'STOCK', 'PLN', 0),
    ('FOX',  'Space Fox Games Spolka Akcyjna',                                   'STOCK', 'PLN', 0),
    ('FPO',  'Forposta S.A.',                                                    'STOCK', 'PLN', 0),
    ('FRB',  'Forbuild SA',                                                      'STOCK', 'PLN', 0),
    ('FRM',  'Freemind Spolka Akcyjna',                                          'STOCK', 'PLN', 0),
    ('FRW',  'Frozen Way Spolka Akcyjna',                                        'STOCK', 'PLN', 0),
    ('FTH',  'Fintech S.A.',                                                     'STOCK', 'PLN', 0),
    ('FTL',  'Foothills S.A.',                                                   'STOCK', 'PLN', 0),
    ('FVE',  'Foto Volt Eko Energia S.A.',                                       'STOCK', 'PLN', 0),
    ('GAL',  'Galvo S.A.',                                                       'STOCK', 'PLN', 0),
    ('GAR',  'Garin S.A.',                                                       'STOCK', 'PLN', 0),
    ('GDC',  'Gamedust S.A.',                                                    'STOCK', 'PLN', 0),
    ('GDS',  'G-Devs Spolka Akcyjna',                                            'STOCK', 'PLN', 0),
    ('GHT',  'Gamehunters Spolka Akcyjna',                                       'STOCK', 'PLN', 0),
    ('GHY',  'Global Hydrogen S.A.',                                             'STOCK', 'PLN', 0),
    ('GKS',  'GKS GieKSa Katowice S.A.',                                        'STOCK', 'PLN', 0),
    ('GME',  'Gremi Media S.A.',                                                 'STOCK', 'PLN', 0),
    ('GMT',  'Genomtec S.A.',                                                    'STOCK', 'PLN', 0),
    ('GMV',  'Gamivo S.A.',                                                      'STOCK', 'PLN', 0),
    ('GMZ',  'Grupa Modne Zakupy S.A.',                                          'STOCK', 'PLN', 0),
    ('GNS',  'Grupa Niewiadow - PGM S.A.',                                       'STOCK', 'PLN', 0),
    ('GOB',  'Gobarto S.A.',                                                     'STOCK', 'PLN', 0),
    ('GRL',  'Green Lanes S.A.',                                                 'STOCK', 'PLN', 0),
    ('GRM',  'Grempco Spolka Akcyjna',                                           'STOCK', 'PLN', 0),
    ('GRZ',  'Green Zebras Spolka Akcyjna',                                      'STOCK', 'PLN', 0),
    ('GTF',  'GO24.pl S.A.',                                                     'STOCK', 'PLN', 0),
    ('GTS',  'Geotrans S.A.',                                                    'STOCK', 'PLN', 0),
    ('GVT',  'Grupa Virtus Spolka Akcyjna',                                      'STOCK', 'PLN', 0),
    ('GX1',  'genXone S.A.',                                                     'STOCK', 'PLN', 0),
    ('HEN',  'HyEnergy S.A.',                                                    'STOCK', 'PLN', 0),
    ('HER',  'Highlander Enterprise S.A.',                                       'STOCK', 'PLN', 0),
    ('HMP',  'Hemp & Health S.A.',                                               'STOCK', 'PLN', 0),
    ('HPE',  'hiPower Energy SA',                                                'STOCK', 'PLN', 0),
    ('HPS',  'Hydrapres S.A.',                                                   'STOCK', 'PLN', 0),
    ('HRC',  'Grupa HRC Spolka Akcyjna',                                         'STOCK', 'PLN', 0),
    ('HRT',  'Hurtimex SA',                                                      'STOCK', 'PLN', 0),
    ('HUB',  'Hub.Tech SA',                                                      'STOCK', 'PLN', 0),
    ('IBC',  'IBC POLSKA F & P Spolka Akcyjna',                                  'STOCK', 'PLN', 0),
    ('IBS',  'WISE Finance S.A.',                                                'STOCK', 'PLN', 0),
    ('ICD',  'Intercapital Property Development ADSIC',                          'STOCK', 'PLN', 0),
    ('ICE',  'Medinice S.A.',                                                    'STOCK', 'PLN', 0),
    ('ICG',  'Ice Code Games S.A.',                                              'STOCK', 'PLN', 0),
    ('IDH',  'IDH Development S.A.',                                             'STOCK', 'PLN', 0),
    ('IDM',  'IDM Spolka Akcyjna',                                               'STOCK', 'PLN', 0),
    ('IFA',  'Generationis.Ai S.A.',                                             'STOCK', 'PLN', 0),
    ('IFR',  'Investment Friends SE',                                            'STOCK', 'PLN', 0),
    ('IGT',  'Igoria Trade S.A.',                                                'STOCK', 'PLN', 0),
    ('IMG',  'Immersion Games S.A.',                                             'STOCK', 'PLN', 0),
    ('IMP',  'Imperio Alternatywna Spolka Inwestycyjna S.A.',                    'STOCK', 'PLN', 0),
    ('INM',  'InventionMed S.A.',                                                'STOCK', 'PLN', 0),
    ('INS',  'Indos SA',                                                         'STOCK', 'PLN', 0),
    ('INT',  'Internity S.A.',                                                   'STOCK', 'PLN', 0),
    ('IPW',  'Image Power S.A.',                                                 'STOCK', 'PLN', 0),
    ('ITB',  'Interbud-Lublin S.A.',                                             'STOCK', 'PLN', 0),
    ('IVE',  'Investeko S.A.',                                                   'STOCK', 'PLN', 0),
    ('IVO',  'Incuvo S.A.',                                                      'STOCK', 'PLN', 0),
    ('IWS',  'Iron Wolf Studio Spolka Akcyjna',                                  'STOCK', 'PLN', 0),
    ('IZO',  'Izolacja Jarocin Spolka Akcyjna',                                  'STOCK', 'PLN', 0),
    ('JJB',  'Jujubee S.A.',                                                     'STOCK', 'PLN', 0),
    ('JRC',  'JRC Group S.A.',                                                   'STOCK', 'PLN', 0),
    ('K2P',  'Kool2play S.A.',                                                   'STOCK', 'PLN', 0),
    ('KCH',  'Krakchemia S.A.',                                                  'STOCK', 'PLN', 0),
    ('KLE',  'Grupa Klepsydra S.A.',                                             'STOCK', 'PLN', 0),
    ('KLN',  'KLON Spolka Akcyjna',                                              'STOCK', 'PLN', 0),
    ('KME',  'Kancelaria Medius S.A.',                                           'STOCK', 'PLN', 0),
    ('KMP',  'Przedsiebiorstwo Produkcyjno-Handlowe KOMPAP S.A.',               'STOCK', 'PLN', 0),
    ('KPC',  'Kupiec S.A.',                                                      'STOCK', 'PLN', 0),
    ('KPD',  'Koszalinskie Przedsiebiorstwo Przemyslu Drzewnego Spolka Akcyjna', 'STOCK', 'PLN', 0),
    ('KPI',  'Kancelaria Prawna-Inkaso WEC Spolka Akcyjna',                      'STOCK', 'PLN', 0),
    ('KSG',  'KSG Agro S.A.',                                                   'STOCK', 'PLN', 0),
    ('KUB',  'Kubota Spolka Akcyjna',                                            'STOCK', 'PLN', 0),
    ('LBD',  'Lokaty Budowlane S.A.',                                            'STOCK', 'PLN', 0),
    ('LBT',  'Libet S.A.',                                                       'STOCK', 'PLN', 0),
    ('LCN',  'Labocanna S.A.',                                                   'STOCK', 'PLN', 0),
    ('LES',  'Less S.A.',                                                        'STOCK', 'PLN', 0),
    ('LET',  'Letus Capital S.A.',                                               'STOCK', 'PLN', 0),
    ('LGT',  'Logintrade S.A.',                                                  'STOCK', 'PLN', 0),
    ('LHD',  'Lichthund Spolka Akcyjna',                                         'STOCK', 'PLN', 0),
    ('LMG',  'Live Motion Games S.A.',                                           'STOCK', 'PLN', 0),
    ('LRQ',  'Larq S.A.',                                                        'STOCK', 'PLN', 0),
    ('LTM',  'Longterm Games S.A.',                                              'STOCK', 'PLN', 0),
    ('LUG',  'LUG S.A.',                                                         'STOCK', 'PLN', 0),
    ('LUK',  'Lukardi S.A.',                                                     'STOCK', 'PLN', 0),
    ('LUO',  'LuON S.A.',                                                        'STOCK', 'PLN', 0),
    ('LXB',  'LexBono S.A.',                                                     'STOCK', 'PLN', 0),
    ('M4B',  'M4B S.A.',                                                         'STOCK', 'PLN', 0),
    ('MAD',  'Madkom SA',                                                        'STOCK', 'PLN', 0),
    ('MAN',  'ManyDev Studio SE',                                                'STOCK', 'PLN', 0),
    ('MAZ',  'Mazop Group Spolka Akcyjna',                                       'STOCK', 'PLN', 0),
    ('MBF',  'MBF Group S.A.',                                                   'STOCK', 'PLN', 0),
    ('MBW',  'Marie Brizard Wine & Spirits SA',                                  'STOCK', 'PLN', 0),
    ('MCR',  'mcr Spolka Akcyjna',                                               'STOCK', 'PLN', 0),
    ('MDA',  'MedApp S.A.',                                                      'STOCK', 'PLN', 0),
    ('MDB',  'Medicofarma Biotech SA',                                           'STOCK', 'PLN', 0),
    ('MDI',  'MDI Energia S.A.',                                                 'STOCK', 'PLN', 0),
    ('MDP',  'Medcamp S.A.',                                                     'STOCK', 'PLN', 0),
    ('MDT',  'MedTech Solutions S.A.',                                           'STOCK', 'PLN', 0),
    ('MEG',  'Megaron S.A.',                                                     'STOCK', 'PLN', 0),
    ('MER',  'Mera S.A.',                                                        'STOCK', 'PLN', 0),
    ('MFD',  'M Food S.A.',                                                      'STOCK', 'PLN', 0),
    ('MGS',  'Madnetic Games Spolka Akcyjna',                                    'STOCK', 'PLN', 0),
    ('MIG',  'Military Group S.A.',                                              'STOCK', 'PLN', 0),
    ('MLK',  'MLK Foods Public Company LTD',                                     'STOCK', 'PLN', 0),
    ('MLM',  'Milisystem S.A.',                                                  'STOCK', 'PLN', 0),
    ('MLP',  'Milkpol Spolka Akcyjna',                                           'STOCK', 'PLN', 0),
    ('MLT',  'Moonlit S.A.',                                                     'STOCK', 'PLN', 0),
    ('MMC',  'MM Conferences S.A.',                                              'STOCK', 'PLN', 0),
    ('MMS',  'Madmind Studio Spolka Akcyjna',                                    'STOCK', 'PLN', 0),
    ('MND',  'Mineral Midrange S.A.',                                            'STOCK', 'PLN', 0),
    ('MO2',  'Moliera2 S.A.',                                                    'STOCK', 'PLN', 0),
    ('MOJ',  'MOJ S.A.',                                                         'STOCK', 'PLN', 0),
    ('MOV',  'Movie Games S.A.',                                                 'STOCK', 'PLN', 0),
    ('MPS',  'MegaPixel Studio S.A.',                                            'STOCK', 'PLN', 0),
    ('MRH',  'Mr Hamburger S.A.',                                                'STOCK', 'PLN', 0),
    ('MRK',  'Marka S.A.',                                                       'STOCK', 'PLN', 0),
    ('MSM',  'Massmedica S.A.',                                                  'STOCK', 'PLN', 0),
    ('MTN',  'Milton Essex Spolka Akcyjna',                                      'STOCK', 'PLN', 0),
    ('MUN',  'Munar S.A.',                                                       'STOCK', 'PLN', 0),
    ('MWT',  'M.W. Trade SA',                                                    'STOCK', 'PLN', 0),
    ('MXC',  'Maxcom S.A.',                                                      'STOCK', 'PLN', 0),
    ('MXP',  'Maxipizza SA',                                                     'STOCK', 'PLN', 0),
    ('MZA',  'Muza S.A.',                                                        'STOCK', 'PLN', 0),
    ('NCL',  'NOCTILUCA Spolka Akcyjna',                                         'STOCK', 'PLN', 0),
    ('NNG',  'NanoGroup S.A.',                                                   'STOCK', 'PLN', 0),
    ('NOB',  'Noobz from Poland S.A.',                                           'STOCK', 'PLN', 0),
    ('NOV',  'NOVINA pozyczkihipoteczne.eu S.A.',                                'STOCK', 'PLN', 0),
    ('NRS',  'Neurone Studio S.A.',                                              'STOCK', 'PLN', 0),
    ('NST',  'Nestmedic S.A.',                                                   'STOCK', 'PLN', 0),
    ('NTC',  'New Tech Capital S.A.',                                            'STOCK', 'PLN', 0),
    ('NTS',  'Notoria Serwis S.A.',                                              'STOCK', 'PLN', 0),
    ('NTU',  'Novaturas AB',                                                     'STOCK', 'PLN', 0),
    ('NTV',  'New Tech Venture S.A.',                                            'STOCK', 'PLN', 0),
    ('NVG',  'Novavis Group S.A.',                                               'STOCK', 'PLN', 0),
    ('NWA',  'NWAI Dom Maklerski S.A.',                                          'STOCK', 'PLN', 0),
    ('NXB',  'Nextbike Polska S.A.',                                             'STOCK', 'PLN', 0),
    ('NXG',  'Nexity Global S.A.',                                               'STOCK', 'PLN', 0),
    ('O2T',  'One2Tribe S.A.',                                                   'STOCK', 'PLN', 0),
    ('OLY',  'Olymp S.A.',                                                       'STOCK', 'PLN', 0),
    ('ONC',  'ONICO S.A.',                                                       'STOCK', 'PLN', 0),
    ('ONE',  'One Solution S.A.',                                                'STOCK', 'PLN', 0),
    ('ONO',  'onesano S.A.',                                                     'STOCK', 'PLN', 0),
    ('OPI',  'Optigis S.A.',                                                     'STOCK', 'PLN', 0),
    ('ORG',  'ORGANIC Farma Zdrowia S.A.',                                       'STOCK', 'PLN', 0),
    ('ORL',  'Orzel Spolka Akcyjna',                                             'STOCK', 'PLN', 0),
    ('OUT',  'Outdoorzy S.A.',                                                   'STOCK', 'PLN', 0),
    ('OVI',  'Ovid Works S.A.',                                                  'STOCK', 'PLN', 0),
    ('OZE',  'OZE Capital S.A.',                                                 'STOCK', 'PLN', 0),
    ('P24',  'Present24 S.A.',                                                   'STOCK', 'PLN', 0),
    ('P2B',  'Planet B2B S.A.',                                                  'STOCK', 'PLN', 0),
    ('P2C',  'Play2Chill S.A.',                                                  'STOCK', 'PLN', 0),
    ('PAC',  'Proacta S.A.',                                                     'STOCK', 'PLN', 0),
    ('PBF',  'PBS Finanse S.A.',                                                 'STOCK', 'PLN', 0),
    ('PBG',  'PBG S.A.',                                                         'STOCK', 'PLN', 0),
    ('PBT',  'Prime Bit Games S.A.',                                             'STOCK', 'PLN', 0),
    ('PDG',  'Pyramid Games S.A.',                                               'STOCK', 'PLN', 0),
    ('PGG',  'Proguns Group S.A.',                                               'STOCK', 'PLN', 0),
    ('PGM',  'PMPG Polskie Media SA',                                            'STOCK', 'PLN', 0),
    ('PGV',  'PGF Polska Grupa Fotowoltaiczna SA',                               'STOCK', 'PLN', 0),
    ('PIT',  'Polaris IT Group S.A.',                                            'STOCK', 'PLN', 0),
    ('PIX',  'Second Chamber S.A.',                                              'STOCK', 'PLN', 0),
    ('PLG',  'PL Group S.A.',                                                    'STOCK', 'PLN', 0),
    ('PLM',  'Polman S.A.',                                                      'STOCK', 'PLN', 0),
    ('PLT',  'Plot Twist SA',                                                    'STOCK', 'PLN', 0),
    ('PLZ',  'Plaza Centers N.V.',                                               'STOCK', 'PLN', 0),
    ('PNT',  'Pointpack S.A.',                                                   'STOCK', 'PLN', 0),
    ('PRA',  'Prime Alternatywna Spolka Inwestycyjna Spolka Akcyjna',            'STOCK', 'PLN', 0),
    ('PRH',  'Red Dev Studio S.A.',                                              'STOCK', 'PLN', 0),
    ('PRI',  'Pragma Inkaso S.A.',                                               'STOCK', 'PLN', 0),
    ('PRN',  'Partner-Nieruchomosci S.A.',                                       'STOCK', 'PLN', 0),
    ('PRO',  'A.P.N. Promise S.A.',                                              'STOCK', 'PLN', 0),
    ('PRS',  'Prymus S.A.',                                                      'STOCK', 'PLN', 0),
    ('PTN',  'Poltronic S.A.',                                                   'STOCK', 'PLN', 0),
    ('PTW',  'Polskie Towarzystwo Wspierania Przedsiebiorczosci S.A.',           'STOCK', 'PLN', 0),
    ('QON',  'QuarticOn Spolka Akcyjna',                                         'STOCK', 'PLN', 0),
    ('QRT',  'Quart Development S.A.',                                           'STOCK', 'PLN', 0),
    ('QUB',  'QubicGames S.A.',                                                  'STOCK', 'PLN', 0),
    ('RBS',  'Robinson Europe S.A.',                                             'STOCK', 'PLN', 0),
    ('RCA',  'Rocca S.A.',                                                       'STOCK', 'PLN', 0),
    ('RCM',  'Red Carpet Media Group S.A.',                                      'STOCK', 'PLN', 0),
    ('RCW',  'Ruch Chorzow S.A.',                                                'STOCK', 'PLN', 0),
    ('RDG',  'Read-Gene S.A.',                                                   'STOCK', 'PLN', 0),
    ('RDN',  'Redan S.A.',                                                       'STOCK', 'PLN', 0),
    ('RGL',  'Robs Group Logistic Spolka Akcyjna',                               'STOCK', 'PLN', 0),
    ('RHD',  'Reinhold Europe AB (publ)',                                        'STOCK', 'PLN', 0),
    ('RNC',  'REINO Capital S.A.',                                               'STOCK', 'PLN', 0),
    ('RND',  'Render Cube S.A.',                                                 'STOCK', 'PLN', 0),
    ('RNT',  'Private Rented Sector S.A.',                                       'STOCK', 'PLN', 0),
    ('RRH',  'RRH Group S.A.',                                                   'STOCK', 'PLN', 0),
    ('RSG',  'Red Square Games S.A.',                                            'STOCK', 'PLN', 0),
    ('RSP',  'Remor Solar Polska S.A.',                                          'STOCK', 'PLN', 0),
    ('RST',  'Road Studio Spolka Akcyjna',                                       'STOCK', 'PLN', 0),
    ('S4E',  'S4E S.A.',                                                         'STOCK', 'PLN', 0),
    ('SBE',  'SoftBlue SA',                                                      'STOCK', 'PLN', 0),
    ('SCS',  'Stem Cells Spin S.A.',                                             'STOCK', 'PLN', 0),
    ('SDS',  'SDS Optic Spolka Akcyjna',                                         'STOCK', 'PLN', 0),
    ('SED',  'Sedivio S.A.',                                                     'STOCK', 'PLN', 0),
    ('SEN',  'Serinus Energy plc',                                               'STOCK', 'PLN', 0),
    ('SEV',  'Sevenet S.A.',                                                     'STOCK', 'PLN', 0),
    ('SFS',  'Sfinks Polska S.A.',                                               'STOCK', 'PLN', 0),
    ('SHD',  'Soho Development S.A.',                                            'STOCK', 'PLN', 0),
    ('SHG',  'Starhedge S.A.',                                                   'STOCK', 'PLN', 0),
    ('SIM',  'SimFabric S.A.',                                                   'STOCK', 'PLN', 0),
    ('SIN',  'Solar Innovation S.A.',                                            'STOCK', 'PLN', 0),
    ('SKN',  'Sakana S.A.',                                                      'STOCK', 'PLN', 0),
    ('SKY',  'Stohid Technology S.A.',                                           'STOCK', 'PLN', 0),
    ('SLT',  'Saule Technologies S.A.',                                          'STOCK', 'PLN', 0),
    ('SMT',  'Simteract S.A.',                                                   'STOCK', 'PLN', 0),
    ('SNG',  'Synerga.Fund S.A.',                                                'STOCK', 'PLN', 0),
    ('SNN',  'Sunway Network S.A.',                                              'STOCK', 'PLN', 0),
    ('SNW',  'Sanwil Holding Spolka Akcyjna',                                    'STOCK', 'PLN', 0),
    ('SOK',  'SONKA S.A.',                                                       'STOCK', 'PLN', 0),
    ('STA',  'Starward Industries Spolka Akcyjna',                               'STOCK', 'PLN', 0),
    ('STD',  'Standrew S.A.',                                                    'STOCK', 'PLN', 0),
    ('STS',  'Satis Group S.A.',                                                 'STOCK', 'PLN', 0),
    ('SUN',  'Suntech S.A.',                                                     'STOCK', 'PLN', 0),
    ('SYG',  'Sygnis SA',                                                        'STOCK', 'PLN', 0),
    ('SZR',  'SZAR Spolka Akcyjna',                                              'STOCK', 'PLN', 0),
    ('TBL',  'T-Bull S.A.',                                                      'STOCK', 'PLN', 0),
    ('TCR',  'Tech Robotics S.A.',                                               'STOCK', 'PLN', 0),
    ('TEC',  'Tecnovatica S.A.',                                                 'STOCK', 'PLN', 0),
    ('TGG',  'Triggo S.A.',                                                      'STOCK', 'PLN', 0),
    ('TGS',  'True Games Syndicate S.A.',                                        'STOCK', 'PLN', 0),
    ('THD',  'The Dust S.A.',                                                    'STOCK', 'PLN', 0),
    ('THG',  'TenderHut S.A.',                                                   'STOCK', 'PLN', 0),
    ('TLG',  'Przedsiebiorstwo Telekomunikacyjne TELGAM S.A.',                   'STOCK', 'PLN', 0),
    ('TLO',  'Telesto S.A.',                                                     'STOCK', 'PLN', 0),
    ('TLS',  'Telestrada SA',                                                    'STOCK', 'PLN', 0),
    ('TME',  'Termoexpert Spolka Akcyjna',                                       'STOCK', 'PLN', 0),
    ('TMP',  'Telemedycyna Polska S.A.',                                         'STOCK', 'PLN', 0),
    ('TNT',  'T&T Proenergy S.A.',                                               'STOCK', 'PLN', 0),
    ('TOS',  'Tamex Obiekty Sportowe S.A.',                                      'STOCK', 'PLN', 0),
    ('TOW',  'Tower Investments S.A.',                                           'STOCK', 'PLN', 0),
    ('TRI',  'Triton Development S.A.',                                          'STOCK', 'PLN', 0),
    ('TRR',  'Termo-Rex S.A.',                                                   'STOCK', 'PLN', 0),
    ('TRX',  'TREX S.A.',                                                        'STOCK', 'PLN', 0),
    ('TXN',  'Tax-Net S.A.',                                                     'STOCK', 'PLN', 0),
    ('UFC',  'Unified Factory S.A.',                                             'STOCK', 'PLN', 0),
    ('UFG',  'UF GAMES S.A.',                                                    'STOCK', 'PLN', 0),
    ('UNF',  'Unfold.vc ASI S.A.',                                               'STOCK', 'PLN', 0),
    ('UNV',  'Universe Spolka Akcyjna',                                          'STOCK', 'PLN', 0),
    ('URT',  'Urteste S.A.',                                                     'STOCK', 'PLN', 0),
    ('VAI',  'Detalion Games S.A.',                                              'STOCK', 'PLN', 0),
    ('VAR',  'VARSAV Game Studios S.A.',                                         'STOCK', 'PLN', 0),
    ('VDS',  'ViDiS S.A.',                                                       'STOCK', 'PLN', 0),
    ('VEE',  'Vee S.A.',                                                         'STOCK', 'PLN', 0),
    ('VER',  'MPL Verbum S.A.',                                                  'STOCK', 'PLN', 0),
    ('VFA',  'VRFabric SA',                                                      'STOCK', 'PLN', 0),
    ('VLT',  'VOOLT Spolka Akcyjna',                                             'STOCK', 'PLN', 0),
    ('VRB',  'Verbicom S.A.',                                                    'STOCK', 'PLN', 0),
    ('VRF',  'VR Factory Games S.A.',                                            'STOCK', 'PLN', 0),
    ('WGP',  'W.G Partners S.A.',                                                'STOCK', 'PLN', 0),
    ('WHH',  'Werth-Holz S.A.',                                                  'STOCK', 'PLN', 0),
    ('WLI',  'Wildlands Interactive S.A.',                                       'STOCK', 'PLN', 0),
    ('WPR',  'Woodpecker.co S.A.',                                               'STOCK', 'PLN', 0),
    ('WRL',  'Wierzyciel S.A.',                                                  'STOCK', 'PLN', 0),
    ('XBS',  'XBS PRO-LOG S.A.',                                                 'STOCK', 'PLN', 0),
    ('XDD',  'Mentzen S.A.',                                                     'STOCK', 'PLN', 0),
    ('YOS',  'Yoshi Innovation S.A.',                                            'STOCK', 'PLN', 0),
    ('YRL',  'yarrl S.A.',                                                       'STOCK', 'PLN', 0),
    ('ZEN',  'Zeneris Projekty S.A.',                                            'STOCK', 'PLN', 0),
    ('ZRE',  'Zaklad Budowy Maszyn ZREMB - Chojnice S.A.',                       'STOCK', 'PLN', 0),
    ('ZRX',  'Zortrax S.A.',                                                     'STOCK', 'PLN', 0),
    ('ZUK',  'Zaklady Urzadzen Kotlowych Staporkow S.A.',                        'STOCK', 'PLN', 0),

    -- === Additional GPW ETFs (Beta Securities / AgioFunds TFI) ===
    ('ETFBW20TR', 'Beta ETF WIG20TR',                    'ETF',   'PLN', 0),
    ('ETFBM40TR', 'Beta ETF mWIG40TR',                   'ETF',   'PLN', 0),
    ('ETFBS80TR', 'Beta ETF sWIG80TR',                   'ETF',   'PLN', 0),
    ('ETFBW20LV', 'Beta ETF WIG20 Lev',                  'ETF',   'PLN', 0),
    ('ETFBW20ST', 'Beta ETF WIG20 Short',                'ETF',   'PLN', 0),
    ('ETFBTBSP',  'Beta ETF TBSP',                       'ETF',   'PLN', 0),
    ('ETFBTCPL',  'Beta ETF Bitcoin',                    'ETF',   'PLN', 0),
    ('ETFBCASH',  'Beta ETF Obligacji 6M',               'ETF',   'PLN', 0),
    ('ETFBDIVPL', 'Beta ETF Dywidendowy',                'ETF',   'PLN', 0),
    ('ETFBNATO',  'Future of Defence UCITS ETF',         'ETF',   'PLN', 0),
    ('ETFBNQ3LV', 'Beta ETF Nasdaq-100 3x Leveraged',   'ETF',   'PLN', 0)
ON CONFLICT (symbol) DO NOTHING;

-- ============================================================================
-- END OF MIGRATION V7
-- Total: 384 GPW stocks + 11 ETFs = 395 new instruments
-- Combined with V6: ~743 instruments total
-- ============================================================================
